version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - tadayosi
      - phantomjinx
      - jsolovjo
      - grgrzybek
      - kariuwu
      - joshiraezcode
  - package-ecosystem: npm
    directory: '/console'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - tadayosi
      - phantomjinx
      - jsolovjo
      - grgrzybek
      - kariuwu
      - joshiraezcode
  - package-ecosystem: npm
    directory: '/console-minimal'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - tadayosi
      - phantomjinx
      - jsolovjo
      - grgrzybek
      - kariuwu
      - joshiraezcode
  - package-ecosystem: npm
    directory: '/examples/sample-plugin'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - tadayosi
      - phantomjinx
      - jsolovjo
      - grgrzybek
      - kariuwu
      - joshiraezcode
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - tadayosi
      - phantomjinx
      - jsolovjo
      - grgrzybek
      - kariuwu
      - joshiraezcode
